# Generated by Django 4.1 on 2022-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('content', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='media/%y/%m/%d')),
                ('category', models.CharField(choices=[('NFT', 'NFT'), ('Smart_contract', 'Smart contract'), ('Other', 'Other')], default='Choose a category', max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
