# Generated by Django 4.1 on 2022-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Isekai collection', 'Isekai collection'), ('DigiDaigaku Genesis', 'DigiDaigaku Genesis'), ('Otherdeed', 'Otherdeed'), ('', '')], default='Choose a category', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
