# Generated by Django 4.1 on 2022-09-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Isekai collection', 'Isekai collection'), ('DigiDaigaku Genesis', 'DigiDaigaku Genesis'), ('Otherdeed', 'Otherdeed'), ('Invisible Friends', 'Invisible Friends')], default='Choose a category', max_length=25),
        ),
    ]
